import type { Lead, Post, Response } from "./temp_types"

// Mock posts
const mockPosts: Post[] = [
  {
    id: 1,
    type: "image",
    content: "/placeholder.svg?height=200&width=200",
    date: "2023-04-15",
  },
  {
    id: 2,
    type: "text",
    content: "האם אתם מחפשים דירה חדשה? יש לנו הצעות מיוחדות לחודש הקרוב! השאירו פרטים ונחזור אליכם בהקדם.",
    date: "2023-04-10",
  },
  {
    id: 3,
    type: "video",
    content: "/video-placeholder.mp4",
    date: "2023-04-05",
  },
  {
    id: 4,
    type: "image",
    content: "/placeholder.svg?height=200&width=200",
    date: "2023-03-28",
  },
  {
    id: 5,
    type: "text",
    content: "מבצע מיוחד לחברי הקבוצה! 10% הנחה על כל הדירות החדשות שלנו. לפרטים נוספים השאירו הודעה.",
    date: "2023-03-20",
  },
]

// Mock leads
export const mockLeads: Lead[] = [
  {
    id: 1,
    fullName: "ישראל ישראלי",
    email: "israel@example.com",
    phone: "050-1234567",
    source: "פוסט",
    date: "2023-04-16",
    status: "חדש",
    autoResponse: true,
    autoResponseChannel: "אימייל",
    convertedFromResponse: false,
    post: mockPosts[0],
    postId: 1,
  },
  {
    id: 2,
    fullName: "שרה כהן",
    email: "sarah@example.com",
    phone: "052-7654321",
    source: "טופס",
    date: "2023-04-15",
    status: "פתוח",
    autoResponse: true,
    autoResponseChannel: "SMS",
    convertedFromResponse: true,
    post: mockPosts[1],
    postId: 2,
  },
  {
    id: 3,
    fullName: "דוד לוי",
    email: "david@example.com",
    phone: "054-1112233",
    source: "קמפיין",
    date: "2023-04-14",
    status: "סגור",
    autoResponse: false,
    convertedFromResponse: false,
    post: mockPosts[2],
    postId: 3,
  },
  {
    id: 4,
    fullName: "רחל אברהם",
    email: "rachel@example.com",
    phone: "053-3334444",
    source: "פוסט",
    date: "2023-04-13",
    status: "חדש",
    autoResponse: true,
    autoResponseChannel: "וואטסאפ",
    convertedFromResponse: false,
    post: mockPosts[0],
    postId: 1,
  },
  {
    id: 5,
    fullName: "יעקב פרץ",
    email: "yaakov@example.com",
    phone: "050-5556666",
    source: "טופס",
    date: "2023-04-12",
    status: "פתוח",
    autoResponse: true,
    autoResponseChannel: "אימייל",
    convertedFromResponse: false,
    post: mockPosts[3],
    postId: 4,
  },
  {
    id: 6,
    fullName: "מיכל גולן",
    email: "michal@example.com",
    phone: "052-7778888",
    source: "קמפיין",
    date: "2023-04-11",
    status: "סגור",
    autoResponse: false,
    convertedFromResponse: true,
    post: mockPosts[4],
    postId: 5,
  },
]

// Mock responses
export const mockResponses: Response[] = [
  {
    id: 1,
    name: "יוסי כהן",
    text: "אני מעוניין בדירה החדשה, אפשר פרטים נוספים?",
    platform: "פייסבוק",
    date: "2023-04-16T10:30:00",
    post: mockPosts[0],
    status: "ידנית",
    convertedToLead: true,
    autoTag: "מעוניין",
  },
  {
    id: 2,
    name: "דנה לוי",
    text: "מה המחיר של הדירות?",
    platform: "אינסטגרם",
    date: "2023-04-15T14:45:00",
    post: mockPosts[1],
    status: "אוטומטית",
    convertedToLead: false,
    autoTag: "שאלה",
  },
  {
    id: 3,
    name: "אבי ישראלי",
    text: "הדירות נראות מעולות! אשמח לשמוע עוד",
    platform: "פייסבוק",
    date: "2023-04-15T09:15:00",
    post: mockPosts[2],
    status: "לא טופל",
    convertedToLead: false,
    autoTag: "מעוניין",
  },
  {
    id: 4,
    name: "שירה גולן",
    text: "האם יש אפשרות לראות את הדירה בשבוע הבא?",
    platform: "אינסטגרם",
    date: "2023-04-14T16:20:00",
    post: mockPosts[0],
    status: "ידנית",
    convertedToLead: true,
    autoTag: "שאלה",
  },
  {
    id: 5,
    name: "יעל פרץ",
    text: "המחירים שלכם גבוהים מדי!",
    platform: "פייסבוק",
    date: "2023-04-13T11:10:00",
    post: mockPosts[3],
    status: "אוטומטית",
    convertedToLead: false,
    autoTag: "ספאם",
  },
  {
    id: 6,
    name: "אלון דוד",
    text: "אני מחפש דירה באזור המרכז, יש לכם משהו שם?",
    platform: "אינסטגרם",
    date: "2023-04-12T13:30:00",
    post: mockPosts[4],
    status: "לא טופל",
    convertedToLead: false,
    autoTag: "שאלה",
  },
]

// Mock post analytics
export const mockPostAnalytics: { [key: number]: any[] } = {
  1: [
    { date: "01/04", leads: 2, responses: 5 },
    { date: "02/04", leads: 3, responses: 8 },
    { date: "03/04", leads: 5, responses: 12 },
    { date: "04/04", leads: 4, responses: 10 },
    { date: "05/04", leads: 6, responses: 15 },
    { date: "06/04", leads: 8, responses: 18 },
    { date: "07/04", leads: 7, responses: 20 },
  ],
  2: [
    { date: "01/04", leads: 1, responses: 3 },
    { date: "02/04", leads: 2, responses: 6 },
    { date: "03/04", leads: 3, responses: 9 },
    { date: "04/04", leads: 2, responses: 7 },
    { date: "05/04", leads: 4, responses: 11 },
    { date: "06/04", leads: 5, responses: 14 },
    { date: "07/04", leads: 4, responses: 12 },
  ],
  3: [
    { date: "01/04", leads: 0, responses: 2 },
    { date: "02/04", leads: 1, responses: 4 },
    { date: "03/04", leads: 2, responses: 7 },
    { date: "04/04", leads: 1, responses: 5 },
    { date: "05/04", leads: 3, responses: 8 },
    { date: "06/04", leads: 2, responses: 6 },
    { date: "07/04", leads: 4, responses: 10 },
  ],
  4: [
    { date: "01/04", leads: 4, responses: 10 },
    { date: "02/04", leads: 5, responses: 13 },
    { date: "03/04", leads: 7, responses: 17 },
    { date: "04/04", leads: 6, responses: 15 },
    { date: "05/04", leads: 8, responses: 20 },
    { date: "06/04", leads: 10, responses: 23 },
    { date: "07/04", leads: 9, responses: 25 },
  ],
  5: [
    { date: "01/04", leads: 3, responses: 7 },
    { date: "02/04", leads: 4, responses: 10 },
    { date: "03/04", leads: 6, responses: 14 },
    { date: "04/04", leads: 5, responses: 12 },
    { date: "05/04", leads: 7, responses: 16 },
    { date: "06/04", leads: 9, responses: 19 },
    { date: "07/04", leads: 8, responses: 22 },
  ],
}